global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ML Pipeline Application
  - job_name: 'ml-pipeline'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # System metrics (if node_exporter is running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom ML metrics endpoint
  - job_name: 'ml-metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 60s
    metrics_path: '/ml-metrics'
